### ISSUE TITLE
getEndpoint cannot guarantee to static analysis, the methods on the returned object. 

### ISSUE THREAD

**Issue by apotek** [ChromaticHQ/orange-dam-php#26]
## Description

I think I made a mistake in deprecating dataTable() and search() and assetLink()  etc… Because by calling `getEndpoint()` I can no longer contractually guarantee to PHPStan that the returned endpoint has the method I am later calling. Consider this example:

```php
$myEndpoint = $this->ApiConnection->getEndpoint('MyEndpoint');
$myEndpoint->doSomething();
```

Since `getEndpoint()` can return any number of different endpoint types, it can only promise to return the abstract ‘Endpoint’ class and not specific subclasses, which means that PHPStan doesn’t know that `getEndpoint('Search')` will return a `Search` endpoint, and therefore PHPStan does not know what methods were added to `Search` that do not exist on Endpoint.

One _could_ attach these methods (unimplemented) to the Endpoint abstract class, but it seems weird to put an Endpoint-specific method signature, even if unimplemented, into an abstract base class.

So either there is a really nifty way to re-declare `getEndpoint()` that will tell PHPStan that the endpoint returned will be the same as the endpoint name passed in `getEndpoint('MyEndpoint');` OR we have to un-deprecate these methods. (ie @dedeprecated :/)

**Comment by apotek** [comment]
So, as an implementor, I can work around this by doing this:

```php
      /** @var \Chromatic\OrangeDam\Endpoints\OAuth2 $oauth */
      $oauth = $this->myOrangeDamConnection->getEndpoint('OAuth2');
      $tokens = $oauth->getTokensByCode(.....);
```

when before we could chain it simply like so:

```php
      $tokens = $this->orangeDamConnection->getEndpoint('OAuth2')->getTokensByCode(...);
```

I feel like unless there is a PHPStan supported way to declare the possible return types in such a way that a static analysis knows that passing 'OAuth2' to `getEndpoint()` will return an 'OAuth2' Endpoint, then we have put end users back a step from where we wanted to be, and de-deprecate these..

So the question is.... How does PHPStan usually handle, for example, the Factory pattern, where `getInstance` can get you any number of different kinds of objects? If it simply doesn't handle that, then dedeprecation is the answer.

**Comment by markdorison** [comment]
I am fine with de-deprecating those methods. In fact, before the final version of your PR, I thought that those methods were going to be the primary way to access the endpoints. So for example, when you add a new endpoint class, you also add a new method to access it in the Factory class.

**Comment by apotek** [comment]
> I am fine with de-deprecating those methods. In fact, before the final version of your PR, I thought that those methods were going to be the primary way to access the endpoints. So for example, when you add a new endpoint class, you also add a new method to access it in the Factory class.

Ok. Posted merge request https://github.com/ChromaticHQ/orange-dam-php/pull/27
