### ISSUE TITLE
Improve Usage of Constants

### ISSUE THREAD

**Issue by adamzimmermann** [ChromaticHQ/orange-dam-php#5]
## Description

@apotek suggested this several months ago and I wanted to officially document now that it has a home.

I had this in my notes:

> add constants to API classes

## Issue Owner
@apotek 

## Acceptance Criteria

I'm not 100% sure what the tactical outcomes were. I'm hoping that @apotek can help define this in more detail.

- [ ] tk…

**Comment by apotek** [comment]
I don't remember enough specifics here any more for this issue to be of any value any longer.
